# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99c4f58dd7b423c1a498e08354543f8e8f1868d4315587c06183c968cb2b40ed9a2c10c8e3a60d96e9fbd5468dbdb709462a74b171c42182cd5e971c142e6275

test:
  secret_key_base: c2b6ef4c05ec78e5671dcb1a2d5156ef6af1ae612acc6ed5004f2aaacfa1909650c344d034452edf4cf98c0f9a7031047f711e912f8441a9f9d1118c70b593ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
